### ISSUE TITLE
Thanks for share and some question

### ISSUE THREAD

**Issue by icelemon1314** [RajanGrewal/MapleResearch#1]
1. Where is the client decode the wz file? it's protect by vm?

**Comment by RajanGrewal** [comment]
No its not VMed at all.  I'm not at my house this week (  no PC, no IDA ) so I will have to get back to you on this later because I cannot remember off the top of my head.  PCOM.dll ResMan.dll are relevant though.

Off Topic:
You can actually get the client to load .img files directly from the Data folder just like BMS Server with like no tweaks. 

I will get back to you on this next week !!

**Comment by RajanGrewal** [comment]
So the client interfaces to WZ files using PCOM.  All WZ nodes and such a COM objects.  PCOM is loaded dynamically into client.  Take a look at `PcCreateObject` function.  Its called in `CWvsApp::InitializeResMan`.  This is where client loads the files. 

One day I will figure out the COM GUIDs and interface to WZ just like the client 😃 But its only a dream for now 😭 TLB file leak plz!!! 😆

**Comment by icelemon1314** [comment]
thanks,i will look it.
